version: '3.9'
networks:
  data:
    external:
      name: waisy

services:
  es:
    container_name: elasticsearch
    hostname: elasticsearch
    image: elasticsearch:7.9.2
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - data
    volumes:
      - ./db/es:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node

#  logstash:
#    container_name: logstash
#    build: ./logstash
##    image: logstash:7.9.3
#    networks:
#      - data
#    volumes:
#      - ./logstash/pipeline:/usr/share/logstash/pipeline
#      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml

  kibana:
    container_name: kibana
    image: kibana:7.3.2
    ports:
      - "5601:5601"
    networks:
      - data
